version: '2.3'
services:
  pool:
    build:
      context: ci
      dockerfile: indy-pool.dockerfile
    ports:
    - "9701-9708:9701-9708"
    # Host networking is used, because we need to know the pool IP at build time, which is kind-of tricky
    network_mode: "host"

# Backend Components
  backend-student:
    depends_on:
      backend-university:
        condition: service_healthy
    build:
      context: student
    ports:
    - "8095:8095"
    environment:
    - RUST_LOG=info
    network_mode: "host"
    healthcheck:
      test: curl -f http://localhost:8095/test/health || exit 1
      interval: 5s
      timeout: 2s
      retries: 35
  backend-university:
    depends_on:
      - pool
    build:
      context: university
    ports:
      - "8090:8090"
    environment:
      - RUST_LOG=info
    network_mode: "host"
    healthcheck:
      test: curl -f http://localhost:8090/test/health || exit 1
      interval: 5s
      timeout: 2s
      retries: 35

# Frontend Components
  frontend-student:
    build:
      context: ../StudyBits-Frontend/student
    network_mode: "host"
    ports:
    - "4200:4200"
  frontend-university:
    build:
      context: ../StudyBits-Frontend/university
    network_mode: "host"
    ports:
    - "4300:4300"

# Backend Integration Tests
  tests:
    build:
      context: integration-tests
    network_mode: "host"
    depends_on:
      backend-student:
        condition: service_healthy
      backend-university:
        condition: service_healthy


